title: Triporate systems status page
baseURL: 'https://status.triporate.com'
languageCode: en
params:
  copyrightHolder: 'Triporate - Travel Outside The Box, S.L.'
  dateFormat: 'January 2, 2006 at 3:04 PM'
  description_footer: >-
    <a class='text-grey-darkest' title='Visit triporate.com'
    href='https://triporate.com/'>triporate.com</a> simplifies Business Travel
    with AI technology.
  description_header: >-
    Information about <a class='text-grey-darkest' title='Visit triporate.com'
    href='https://triporate.com/'>triporate</a> systems operations.<br />Follow
    us <a class='text-grey-darkest' title='Visit our page on Twitter'
    href='https://www.twitter.com/triporate'>on Twitter</a> or subscribe to <a
    class='text-grey-darkest' href='%s' >RSS</a><br />to be alerted of new
    events.
  eventsPerPage: 10
  logo: >-
    https://res.cloudinary.com/chalo/image/upload/v1508925122/brand-triporate-horizontal-rgb-150dpi_1_iovvyd.png
  meta_description: >-
    This status page provides updated information about Triporate's systems
    normal operation, incidents that may happen and their resolution.
  shortDateFormat: '15:04 — Jan 2'
  systems:
    - description: Our company public facing website
      link: 'https://www.triporate.com/'
      name: Website
    - description: Our Travel Engine that renders and manages all trips
      name: AI Travel Engine
    - description: In and out email parsing services
      name: Email Services
  timezoneString: Europe/Madrid
